/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jd2xx_JD2XX_ProgramData */

#ifndef _Included_jd2xx_JD2XX_ProgramData
#define _Included_jd2xx_JD2XX_ProgramData
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
