/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jd2xx_JD2XX_DeviceInfo */

#ifndef _Included_jd2xx_JD2XX_DeviceInfo
#define _Included_jd2xx_JD2XX_DeviceInfo
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
